blank_issues_enabled: false
contact_links:
  - name: KIParla Management
    url: https://github.com/orgs/KIParla/teams/management
    about: Usa questo team per notificare il gruppo di gestione quando necessario.
